DROP SCHEMA PUBLIC CASCADE;

SET DATABASE EVENT LOG LEVEL 3;

DROP TABLE nasdaq_totalview IF EXISTS;

CREATE TABLE nasdaq_totalview  (
    record_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    soup_partition INTEGER,
    soup_sequence INTEGER,
    msg_type LONGVARCHAR,
    symbol_locate INTEGER,
    unique_timestamp INTEGER,
    order_id INTEGER,
    side LONGVARCHAR,
    quantity INTEGER,
    symbol LONGVARCHAR,
    price INTEGER,
    mpid LONGVARCHAR
);